INSERT INTO drv_inventory_item_status_enum (item_status)
    VALUES ('Aged to lost'),
            ('Available'),
            ('Awaiting pickup'),
            ('Awaiting delivery'),
            ('Checked out'),
            ('Claimed returned'),
            ('Declared lost'),
            ('In process'),
            ('In process (non-requestable)'),
            ('In transit'),
            ('Intellectual item'),
            ('Long missing'),
            ('Lost and paid'),
            ('Missing'),
            ('On order'),
            ('Paged'),
            ('Restricted'),
            ('Order closed'),
            ('Unavailable'),
            ('Unknown'),
            ('Withdrawn'
    ) ON CONFLICT (item_status) DO NOTHING;
